version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schedulerNotifications-api
    restart: unless-stopped
    networks:
      - my-external-network
    volumes:
      - .:/app
      - /app/node_modules
networks:
    my-external-network:
        external: true
