version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dservices-notifications
    restart: unless-stopped
    ports:
      - "3200:3200"
    networks:
      - global-network
    volumes:
      - .:/app
      - /app/node_modules
networks:
    global-network:
        external: true